name: CI/CD para Microservicios Modificados

on:
  push:  # Cualquier push a cualquier rama activará el workflow

jobs:
  detectar-cambios:
    runs-on: ubuntu-latest
    outputs:
      servicios_modificados: ${{ steps.set-modified.outputs.modified_services }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Obtener archivos modificados
        id: detect
        uses: tj-actions/changed-files@v34.0.2
        with:
          files: |
            Micros/**

      - name: Establecer servicios modificados
        id: set-modified
        run: |
          modified_services=$(echo "${{ steps.detect.outputs.modified_files }}" | grep -oP '(?<=Micros/)[^/]+' | jq -R -s -c 'split("\n")[:-1]')
          if [ -z "$modified_services" ]; then 
            modified_services="[]" 
          fi
          echo "modified_services=$modified_services" >> $GITHUB_ENV
          echo "modified_services=$modified_services" >> $GITHUB_OUTPUT

  construir-y-desplegar:
    needs: detectar-cambios
    if: ${{ needs.detectar-cambios.outputs.servicios_modificados != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        servicio: ${{ fromJson(needs.detectar-cambios.outputs.servicios_modificados) }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Construir y Desplegar
        run: |
          cd Micros/${{ matrix.servicio }}
          ./build-deploy.sh
